# Generated by Django 4.0.3 on 2022-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-date_added'], 'permissions': [('can_edit', 'Can edit Discussions'), ('can_add', 'Can add Discussions'), ('can_delete', 'Can delete Discussions')]},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added'], 'permissions': [('can_edit', 'Can edit Topics'), ('can_add', 'Can add Topics'), ('can_delete', 'Can delete Topics')]},
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
