# Generated by Django 4.0.3 on 2022-03-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_discussion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added']},
        ),
    ]
