# Generated by Django 4.0.3 on 2022-04-05 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_discussion_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='assoc_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
