# Generated by Django 4.0.3 on 2022-03-19 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
