# Generated by Django 4.0.3 on 2022-03-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feeditem_time_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeditem',
            old_name='discussion',
            new_name='topic',
        ),
    ]
